NAME: carts-db
LAST DEPLOYED: Fri Feb 23 15:51:55 2024
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: dynamodb-local/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: carts-db-dynamodb-local
  labels:
    app.kubernetes.io/name: dynamodb-local
    app.kubernetes.io/instance: carts-db
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: dynamodb-local-1.0.0
---
# Source: dynamodb-local/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: carts-db
  labels:
    app.kubernetes.io/name: dynamodb-local
    app.kubernetes.io/instance: carts-db
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: dynamodb-local-1.0.0
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    
    app.kubernetes.io/name: dynamodb-local
    app.kubernetes.io/instance: carts-db
---
# Source: dynamodb-local/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: carts-db-dynamodb-local
  labels:
    app.kubernetes.io/name: dynamodb-local
    app.kubernetes.io/instance: carts-db
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: dynamodb-local-1.0.0
spec:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  serviceName: "dynamodb"
  selector:
    matchLabels:
      app.kubernetes.io/name: dynamodb-local
      app.kubernetes.io/instance: carts-db
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dynamodb-local
        app.kubernetes.io/instance: carts-db
    spec:
      terminationGracePeriodSeconds: 60
      serviceAccountName: carts-db-dynamodb-local
      securityContext:
        {}
      containers:
        - name: dynamodb-local
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          image: "amazon/dynamodb-local:latest"
          imagePullPolicy: IfNotPresent
          args: [ "-jar", "/home/dynamodblocal/DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data" ]
          env:
          ports:
            - protocol: TCP
              containerPort: 8000
              name: dynamodb
          resources:
            limits:
              cpu: 200m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
          volumeMounts:
            - name:      storage
              mountPath: /data
              subPath:   data
              readOnly:  false
      volumes:
        - name: storage
          emptyDir:
            sizeLimit: 10Gi

