apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "expresso-shop-web.fullname" . }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{- include "expresso-shop-web.selectorLabels" . | nindent 6 }}
