apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  labels:
    {{- include "dynamodb-local.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dynamodb
      protocol: TCP
      name: dynamodb
  selector:
    {{ include "dynamodb-local.selectorLabels" . | nindent 4 }}
