apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    meta.helm.sh/release-name: expresso-shop-reviews
    meta.helm.sh/release-namespace: s6
  creationTimestamp: "2024-01-16T02:30:38Z"
  generation: 3
  labels:
    app.kubernetes.io/instance: expresso-shop-reviews
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: expresso-shop-reviews
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: expresso-shop-reviews-0.1.0
    version: v1
  name: expresso-shop-reviews
  namespace: s6
  resourceVersion: "1579684"
  uid: 26899d4f-9240-4172-a397-e6213721ab36
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: expresso-shop-reviews
      app.kubernetes.io/name: expresso-shop-reviews
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: expresso-shop-reviews
        app.kubernetes.io/name: expresso-shop-reviews
        version: v1
    spec:
      containers:
      - env:
        - name: SERVICE_VERSION
          value: v1
        image: devopseasylearning/s6-expresso-reviews:v1.0.0
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: expresso-shop-reviews
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: expresso-shop-reviews
      serviceAccountName: expresso-shop-reviews
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2024-01-16T02:36:12Z"
    lastUpdateTime: "2024-01-16T02:36:12Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2024-01-16T02:30:38Z"
    lastUpdateTime: "2024-01-16T02:36:58Z"
    message: ReplicaSet "expresso-shop-reviews-749454db57" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
