controller:
  metrics:
     enabled: true
     serviceMonitor:
        enabled: true


dex:
  metrics:
     enabled: true
     serviceMonitor:
        enabled: true


redis:
  metrics:
     enabled: true
     serviceMonitor:
        enabled: true

server:
  metrics:
     enabled: true
     serviceMonitor:
        enabled: true

repoServer:
  metrics:
     enabled: true
     serviceMonitor:
        enabled: true

        

applicationSet:
  metrics:
     enabled: true
     serviceMonitor:
        enabled: true

        
notifications:
  metrics:
     enabled: true
     serviceMonitor:
        enabled: true