apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  labels:
    {{- include "checkout.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "checkout.selectorLabels" . | nindent 4 }}
    APP: {{ .Values.label.app }}
