apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app_name }}-configmap
data:
  JAVA_OPTS: "-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom"
  SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
  ENDPOINTS_CATALOG: "http://catalog:8080"
  ENDPOINTS_CARTS: "http://carts:8080"
  ENDPOINTS_ORDERS: "http://orders:8080"
  ENDPOINTS_CHECKOUT: "http://checkout:8080"
  ENDPOINTS_ASSETS: "http://assets:8080"