apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    {{- include "expresso-shop-reviews.labels_01" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "expresso-shop-reviews.selectorLabels_01" . | nindent 4 }}
    {{- include "expresso-shop-reviews.selectorLabels_02" . | nindent 4 }}
