apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha-db
  template:
    metadata:
      labels:
        app: alpha-db
    spec:
      containers:
        - name: alpha-db
          image: devopseasylearning/apha-db:latest
          imagePullPolicy: Always  # Set the image pull policy to Always
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "BoQU2SSK*PJqYYS8L*w8rDn"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              value: "GzWNQY8eH4YBkt8HutZj@*J"
            - name: MYSQL_DATABASE
              value: "weatherapp"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
      volumes:
        - name: db-data
          hostPath:
            path: /data/db-data

---
apiVersion: v1
kind: Service
metadata:
  name: alpha-db-service
spec:
  selector:
    app: alpha-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
