apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha-ui
  template:
    metadata:
      labels:
        app: alpha-ui
    spec:
      containers:
        - name: alpha-ui
          image: devopseasylearning/apha-ui:latest
          imagePullPolicy: Always  # Set the image pull policy to Always
          env:
            - name: AUTH_HOST
              value: "alpha-auth-service" # Use the service name as the hostname
            - name: AUTH_PORT
              value: "8080"
            - name: WEATHER_HOST
              value: "alpha-weather-service" # Use the service name as the hostname
            - name: WEATHER_PORT
              value: "5000"
            - name: REDIS_USER
              value: "redis"
            - name: REDIS_PASSWORD
              value: "fR*f#V2nBeuVh4#b^F92tat4"
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: alpha-ui-service
spec:
  selector:
    app: alpha-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
