apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app_name }}-configmap
data:
  JAVA_OPTS: "-XX:MaxRAMPercentage=75.0 -Djava.security.egd=file:/dev/urandom"
  SERVER_TOMCAT_ACCESSLOG_ENABLED: "true"
  SPRING_PROFILES_ACTIVE: "rabbitmq"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://orders-db:5432/orders"
  SPRING_RABBITMQ_HOST: "rabbitmq"